### PR TITLE
Added Pause Animation Option

### PR DESCRIPTION
**Pull request by krishnaguragain**
I think this might be helpful to people to manually pause the animation.

### CODE REVIEW

**Comment by megasanjay** [comment]
Thank you for the PR. Would it make more sense to be passed as a method or a prop?

**Comment by krishnaguragain** [comment]
I feel prop is good idea for me.

**Comment by megasanjay** [comment]
Sounds good. Thank you for your contribution. Will merge and release soon.

**Comment by krishnaguragain** [comment]
okay, waiting....

**Comment by megasanjay** [comment]
Released as [version v4.1.0](https://github.com/megasanjay/vue3-marquee/releases/tag/v4.1.0).

**Pull request merged**
